#!/bin/bash
# =============================================================================
# eBPF Monitoring - Deployment Management Script
# =============================================================================
# Usage: ./deploy.sh [command]
# Commands:
#   start     - Start all services
#   stop      - Stop all services
#   restart   - Restart all services
#   logs      - Show logs (follow mode)
#   status    - Show service status
#   clean     - Remove all containers and volumes
#   setup     - Initial setup (create .env, directories)
#   rebuild   - Rebuild and restart epbf-monitor
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

check_env() {
    if [ ! -f "$ENV_FILE" ]; then
        print_warning ".env file not found. Creating from template..."
        cp "$SCRIPT_DIR/.env.example" "$ENV_FILE"
        print_info "Please edit $ENV_FILE with your configuration"
        print_info "Then run: $0 start"
        exit 1
    fi
}

check_docker() {
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed"
        exit 1
    fi
    
    if ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose is not installed"
        exit 1
    fi
}

setup() {
    print_info "Setting up eBPF Monitoring deployment..."
    
    # Create .env if not exists
    if [ ! -f "$ENV_FILE" ]; then
        cp "$SCRIPT_DIR/.env.example" "$ENV_FILE"
        print_success "Created .env file"
    fi
    
    # Create directories
    mkdir -p "$SCRIPT_DIR/postgres/data"
    mkdir -p "$SCRIPT_DIR/garage/data"
    mkdir -p "$SCRIPT_DIR/../build"
    print_success "Created data directories"
    
    # Check if garage config exists
    if [ ! -f "$SCRIPT_DIR/garage/config.toml" ]; then
        print_info "Creating Garage configuration..."
        cat > "$SCRIPT_DIR/garage/config.toml" << 'EOF'
# Garage Configuration File
# Generated by deploy.sh

bind_addr = "0.0.0.0:3900"
rpc_bind_addr = "0.0.0.0:3901"
db_engine = "sqlite"
db_path = "/garage-data/metadata.db"
data_dir = "/garage-data/data"
replication_factor = 1
region = "garage"
EOF
        print_success "Created Garage configuration"
    fi
    
    print_success "Setup complete!"
    print_info "Edit .env file to customize configuration"
    print_info "Then run: $0 start"
}

start() {
    check_env
    check_docker
    
    print_info "Starting eBPF Monitoring services..."
    
    cd "$SCRIPT_DIR"
    docker-compose up -d
    
    print_success "Services started!"
    print_info "Waiting for services to be healthy..."
    sleep 5
    
    # Check service status
    docker-compose ps
    
    print_info ""
    print_info "Access points:"
    print_info "  - epbf-monitor: http://localhost:8080"
    print_info "  - PostgreSQL:   localhost:5432"
    print_info "  - Garage S3:    localhost:3900"
    print_info ""
    print_info "View logs: $0 logs"
}

stop() {
    check_docker
    
    print_info "Stopping eBPF Monitoring services..."
    
    cd "$SCRIPT_DIR"
    docker-compose down
    
    print_success "Services stopped"
}

restart() {
    check_docker
    
    print_info "Restarting eBPF Monitoring services..."
    
    cd "$SCRIPT_DIR"
    docker-compose restart
    
    print_success "Services restarted"
}

logs() {
    check_docker
    
    cd "$SCRIPT_DIR"
    docker-compose logs -f
}

status() {
    check_docker
    
    cd "$SCRIPT_DIR"
    docker-compose ps
}

clean() {
    print_warning "This will remove all containers and volumes!"
    read -p "Are you sure? (y/N): " confirm
    
    if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
        check_docker
        
        print_info "Stopping services..."
        cd "$SCRIPT_DIR"
        docker-compose down -v
        
        print_info "Removing data directories..."
        rm -rf "$SCRIPT_DIR/postgres/data"
        rm -rf "$SCRIPT_DIR/garage/data"
        
        print_success "Cleanup complete"
    else
        print_info "Cancelled"
    fi
}

rebuild() {
    check_docker
    
    print_info "Rebuilding epbf-monitor..."
    
    cd "$SCRIPT_DIR"
    docker-compose build --no-cache epbf-monitor
    docker-compose up -d epbf-monitor
    
    print_success "Rebuild complete"
}

# Main command handler
case "${1:-help}" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    logs)
        logs
        ;;
    status)
        status
        ;;
    clean)
        clean
        ;;
    setup)
        setup
        ;;
    rebuild)
        rebuild
        ;;
    help|*)
        echo "eBPF Monitoring Deployment Script"
        echo ""
        echo "Usage: $0 [command]"
        echo ""
        echo "Commands:"
        echo "  start     - Start all services"
        echo "  stop      - Stop all services"
        echo "  restart   - Restart all services"
        echo "  logs      - Show logs (follow mode)"
        echo "  status    - Show service status"
        echo "  clean     - Remove all containers and volumes"
        echo "  setup     - Initial setup (create .env, directories)"
        echo "  rebuild   - Rebuild and restart epbf-monitor"
        echo ""
        echo "Examples:"
        echo "  $0 setup    # First-time setup"
        echo "  $0 start    # Start services"
        echo "  $0 logs     # View logs"
        ;;
esac
